import { useState, useEffect } from 'react';
import { DashboardData } from '../types';

// This will be replaced with actual data from Python export
// For development, we'll use sample data
const SAMPLE_DATA: DashboardData = {
  monthly: [],
  reasons: [],
  sources: [],
  metrics: [],
};

export function useData() {
  const [data, setData] = useState<DashboardData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadData() {
      try {
        // Try to load from data.json (generated by Python)
        const response = await fetch('/data.json');
        if (response.ok) {
          const jsonData = await response.json();
          setData(jsonData);
        } else {
          console.error('Failed to load data.json:', response.status);
          setError('Failed to load data.json');
        }
      } catch (err) {
        console.error('Error loading data:', err);
        setError('Failed to load data');
      } finally {
        setLoading(false);
      }
    }

    loadData();
  }, []);

  return { data, loading, error };
}

